### PR TITLE
Secure Signature Spoofing

### PR DESCRIPTION
**Pull request by ghost**
Changes the signature spoofing patch to be secure -- it whitelists the package names and signatures of microG, and requires apps to be a system app to even be considered for signature spoofing.

PROOF IT WORKS:

1. apply patch
2. install microG (as system app) and signature spoofing checker
3. microG will say "signature spoofing enabled", while the checker won't

### CODE REVIEW

**Comment by Lanchon** [comment]
hi

thanks! unfortunately i believe this runs contrary to software freedom and thus i won't merge it.

android APK signatures were introduced to allow a decentralized model of app publishing and update. android should have never exposed package signatures to the apps themselves. this is a form of attestation service for the apps that many times runs contrary to what device owners want. an app can query its own signature to check for modifications (think of using apktool) and fail to run or run properly if it is not the software publisher's signature. a binary library can check for a service provider signature to lock out competing implementations of the service (think of GSF). both of these cases restricts the user's freedom to tinker and use the software they want or trust, and the attestation on which they depend should never have been part of the platform if the platform was actually designed for the users instead of for the vendors. android is full of crap like this.

signature spoofing helps modders a bit in this regard. it is sad to see that some projects like lineage4microg chose to lock down sigspoof so only they can benefit from it. i talked to the guys behind l4m about it but they didn't budge. this is why i don't use and can't recommend l4m.

your patch needlessly restrict the platform to use a certain microg build, which is contrary to freedom and good thinking. if you look around you'll see that official microg has historically lagged behind forks badly, and you'll sooner or later very probably want to switch to a fork to fix some issue or fix the issue yourself, and you are locking yourself out of the possibility.

your interests would best be served if you just check for package names instead of signatures: you know which APKs you want to install and choose to do so; no need to lock down on signatures at all.

however even restricting by package name or system app status hinders your ability to tinker with 3rd party apps. several tools to mod apps exist (like apktool or my own dexpatcher suite), but many apps resist modding (against user's will) by querying their own signature to the system and an open sigspoof service solves that issue.

ask yourself:

1) if sigspoof is proven to be important for freedom (you find out when you want to get rid of google), why do you think it's only applicable to one single case?

2) what exactly are you trying to solve with these lockdowns on sigspoof? what kind of attack you think you'll be curtailing by introducing them?

thanks!

**Comment by ghost** [comment]
You make some very good points there, although microG forks will likely use the same fake_signature as the original microG (i checked, for example FakeStore and GmsCore both appear to spoof the same signature)

**Comment by Lanchon** [comment]
sorry i assumed you verified the REAL signature of the apk, not the requested FAKE signature. and absolutely, all microG compilations need to fake the same sig (google's), as this is required for compatibility with the binary client library distributed by google and embedded into all GSF-dependent apps.

**Comment by Lanchon** [comment]
but still, think about question 2 above. many people misunderstand sigspoof.

sigspoof will NOT break android security in any way i'm aware of: the OS will NOT allow updating a "real" app with a "fake sig" one, and it will not allow accessing protected resources of a "real" app from a "fake sig" one with matching signatures (eg: sharing the linux user id, accessing private app data, sharing of protected permissions, etc).

the OS itself never sees or uses the fake sig for any of its functions. it merely attests signatures falsely to apps that care to ask using a functionality that should never have been there in the first place.

if you want some apps to share resources, you must repack all apps involved with your own signature; no sigspoof needed. but if some of those apps use signature attestation as an anti-tampering mechanism, you can defeat the mechanism using sigspoof.

**Pull request closed without merging**
